/** Generated by scripts/sync-icline-docs.mjs — do not edit by hand. */
export const ICLINE_BUILD_METADATA = {
	releaseVersion: "0.1.15",
	devBuildNumber: null,
	devBuildLabel: null,
	builtAt: "2026-06-22 08:25",
	upstreamClineSyncedVersion: "v3.89.2",
	upstreamClineSyncedAt: "2026-06-21",
	upstreamClineRepo: "https://github.com/cline/cline",
} as const
