/** Generated by scripts/sync-icline-docs.mjs — do not edit by hand. */
export const ICLINE_BUILD_METADATA = {
	upstreamClineSyncedVersion: "v3.89.2",
	upstreamClineSyncedAt: "2026-06-21",
	upstreamClineRepo: "https://github.com/cline/cline",
} as const
